/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProductsForm.java
 *
 * Created on 24 Ιαν 2010, 1:54:33 μμ
 */
package View;

import Model.Item;
import Controller.Register;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author alefrag
 */
public class ProductsForm extends javax.swing.JFrame {

    /**
     * Το ταμείο
     */
    private Register register;
    /**
     * Η Αρχική φόρμα 
     */
    private MainStoreForm parentForm;

    /** Creates new form ProductsForm */
    ProductsForm(MainStoreForm parent, Register register) {
        parentForm = parent;
        this.register = register;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jList1.setModel(new ProductListModel());
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Διαθέσιμα προϊόντα");

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));

        jLabel2.setText("Κωδικός");

        jLabel3.setText("Περιγραφή");

        jLabel4.setText("Τιμή");

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setText("-");

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Περιγραφή");

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextField3.setText("0.0");

        jLabel5.setText("Euro");

        jLabel6.setText("Διαθέσιμη ποσότητα");

        jTextField4.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextField4.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(93, 93, 93)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jButton1.setText("Αποθήκευση μεταβολών");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Αποθήκευση Νέου Προϊόντος");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setText("Επιστροφή");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                        .addGap(111, 111, 111))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(5, 5, 5)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Με την επιλογή κάποιου προϊόντος από την λίστα προϊόντων
     * ενημερώνονται τα αντίστοιχα JTextField ωστε ο χειριστής
     * να μπορέσει να πραγματοποιήσει αλλαγές
     *
     */
    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        Item p1 = (Item) jList1.getSelectedValue();
        jTextField1.setText(p1.getltemlD());
        jTextField2.setText(p1.getDescription());
        jTextField3.setText("" + p1.getPrice());
        jTextField4.setText("" + p1.getQuantity());
    }//GEN-LAST:event_jList1ValueChanged

    /**
     * Με την επιλογή του κουμπιού Αποθήκευσης μεταβολών τα στοιχεία του επιλεγμένου
     * προϊόντος ενημερώνονται από τις τιμές που έχει δώσει ο χρήστης
     *
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Ανακτάται η αναφορά στο αντικείμενο του προϊόντος
        Item p1 = (Item) jList1.getSelectedValue();
        //Θέτουμε ως κωδικό προϊόντος το περιεχόμενο του jTextField1
        p1.setItemID(jTextField1.getText());
        //Θέτουμε ως περιγραφή προϊόντος το περιεχόμενο του jTextField2
        p1.setDescription(jTextField2.getText());

        try {
            // Μετατρέπουμε το κείμενο που έδωσε ο χρήστης σε πραγματικούς αριθμούς
            // για τιμή και ποσότητα προϊόντος
            double price = Double.parseDouble(jTextField3.getText());
            double quantity = Double.parseDouble(jTextField4.getText());
            //Ελέγχουμε αν η τιμή και η ποσότητα έχουν θετική τιμή
            if (price > 0 && quantity > 0) {
                //Θέτουμε ως τιμή προϊόντος το περιεχόμενο του jTextField3
                p1.setPrice(price);
                //Θέτουμε ως διαθέσιμη ποσότητα προϊόντος το περιεχόμενο του jTextField4
                p1.setQuantity(quantity);

            //Ενεργοποίησε την αρχική φόρμα
            parentForm.setEnabled(true);
            //Απελευθέρωσε την τρέχουσα φόρμα
            dispose();
            } else 
                throw new Exception();
        } catch (Exception x) {
            //Επειδή ο χρήστης μπορεί να έχει δώσει μη επιτρεπτεί τιμή
            JOptionPane.showMessageDialog(rootPane, "Παρακαλώ βάλτε θετικό πραγματικό " +
                    "αριθμό για το κόστος και την διαθέσιμη ποσότητα");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

     /**
     * Με την επιλογή του κουμπιού Αποθήκευσης νέου προιόντος δημιουργείται νέο
      * προϊόν με τα στοιχεία που έχει δώσει ο χρήστης και εισάγεται στο κατάστημα
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // Μετατρέπουμε το κείμενο που έδωσε ο χρήστης σε πραγματικούς αριθμούς 
            // για τιμή και ποσότητα προϊόντος
            double price = Double.parseDouble(jTextField3.getText());
            double quantity = Double.parseDouble(jTextField4.getText());

            //Ελέγχουμε αν ο κωδικός προϊόντος που έδωσε ο χρήστης στο jTextField1 υπάρχει ήδη
            if (register.getProductCatalog().findProduct(jTextField1.getText()) != null) {
                JOptionPane.showMessageDialog(rootPane, "Ο κωδικός του προϊόντος υπάρχει ήδη");
                return;
            }
            //Ελέγχουμε αν η τιμή και η ποσότητα έχουν θετική τιμή
            if (price <= 0 && quantity <= 0) {
                JOptionPane.showMessageDialog(rootPane, "Παρακαλώ βάλτε θετικό πραγματικό " +
                    "αριθμό για το κόστος και την διαθέσιμη ποσότητα");
                return;
            }
            // Όλα τα στοιχεία είναι σωστά άρα μπορούμε να δημιουργήσουμε το νέο προϊόν
            Item p1 = new Item(jTextField1.getText(),
                    jTextField2.getText(), price, quantity);
            // Εισάγουμε το νέο προϊόν στο μοντέλο στο κατάστημα
            register.getBelongingStore().addProduct(p1);
            // Θα ήταν ισοδύναμο να εισάγουμε το αντικείμενο στο μοντέλο
            // της λίστας γιατί και τα δύο δείχνουν στο ίδιο ArrayList!!!
            //((ProductListModel) jList1.getModel()).addProduct(p1);

            //Ενεργοποίησε την αρχική φόρμα
            parentForm.setEnabled(true);
            //Απελευθέρωσε την τρέχουσα φόρμα
            dispose();
        } catch (NumberFormatException x) {
            JOptionPane.showMessageDialog(rootPane, "Παρακαλώ βάλτε πραγματικό αριθμό για κόστος και ποσότητα");
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    /**
     * Επιστροφή στην αρχική φόρμα αν πατηθεί η ακύρωση
     *
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            //Ενεργοποίησε την αρχική φόρμα
            parentForm.setEnabled(true);
            //Απελευθέρωσε την τρέχουσα φόρμα
            dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

     /**
     * Επιστροφή στην αρχική φόρμα αν πατηθεί το Χ για το κλείσιμο της φόρμας
     *
     */
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
            //Ενεργοποίησε την αρχική φόρμα
            parentForm.setEnabled(true);
            //Απελευθέρωσε την τρέχουσα φόρμα
            dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * Δημιουργούμε ένα εξειδικευμένο μοντέλο λίστας ώστε να μπορούμε να
     * διαθέτουμε αναφορά στην δομή του καταστήματος
     */
    class ProductListModel extends javax.swing.AbstractListModel {

        ArrayList<Item> products = register.getProductCatalog().getProducts();

        public int getSize() {
            return products.size();
        }

        public Object getElementAt(int i) {
            return products.get(i);
        }

        public void addProduct(Item x) {
            products.add(x);
            fireContentsChanged(this, products.size() - 1, products.size() - 1);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
