
package View;

import Model.Receipt;
import Model.Item;
import Model.Store;
import Controller.Register;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.swing.*;

public class SalesForm extends javax.swing.JFrame {
    /**
     * Το ταμείο
     */
    private Register reg;
    /**
     * Η Αρχική φόρμα
     */
    private MainStoreForm parentForm;
    // Για λόγους ευκολίας δημιουργούμε πίνακες με τις τιμές που μπορεί να 
    // επιλέξει ο χρήστης αφού θέλουμε αργότερα στον κώδικα να κάνουμε
    // παρόμοιους ελέγχους και ενέργειες για κάθε ζεύγαρι
    JComboBox[] productSelection = new JComboBox[5];
    JTextField[] productQuantity = new JTextField[5];

    /** Creates new form SalesForm */
    public SalesForm(MainStoreForm parent, Register register) {
        parentForm = parent;
        this.reg = register;
        initComponents();
        //Αρχικοποιούμε τους πίνακες
        productSelection[0] = jComboBox1;
        productQuantity[0] = jTextField1;
        productSelection[1] = jComboBox2;
        productQuantity[1] = jTextField2;
        productSelection[2] = jComboBox3;
        productQuantity[2] = jTextField3;
        productSelection[3] = jComboBox4;
        productQuantity[3] = jTextField4;
        productSelection[4] = jComboBox5;
        productQuantity[4] = jTextField5;

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField(new Date());
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jTextField2 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox();
        jTextField3 = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox();
        jTextField4 = new javax.swing.JTextField();
        jComboBox5 = new javax.swing.JComboBox();
        jTextField5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Ημερομηνια");

        jFormattedTextField1.setEditable(false);
        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        jLabel2.setText("Αρ. Συναλ.");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText(""+(Store.getTransactionId()));

        jLabel4.setText("Προιόν");

        jComboBox1.setModel(new ProductsModel());

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("0");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Ποσότητα");

        jButton1.setText("Ολοκλήρωση Συναλλαγής");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeSale(evt);
            }
        });

        jLabel6.setText("Σύνολο");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("0.0");

        jLabel8.setText("Euro");

        jComboBox2.setModel(new ProductsModel());

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("0");

        jComboBox3.setModel(new ProductsModel());

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("0");

        jComboBox4.setModel(new ProductsModel());

        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("0");

        jComboBox5.setModel(new ProductsModel());

        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("0");

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setText("Ακύρωση");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setText("Ποσό πληρωμής");

        jTextField6.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextField6.setText("0.00");

        jLabel10.setText("Ρέστα: 0.00 Euro");

        jLabel11.setText("Euro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11))
                            .addComponent(jComboBox5, javax.swing.GroupLayout.Alignment.LEADING, 0, 338, Short.MAX_VALUE)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.Alignment.LEADING, 0, 338, Short.MAX_VALUE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.Alignment.LEADING, 0, 338, Short.MAX_VALUE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.LEADING, 0, 338, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, 338, Short.MAX_VALUE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField4)
                            .addComponent(jTextField3)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(jTextField5))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Όταν πατηθεί το κουμπί Ολοκλήρωση Συναλλαγής δημιουργείται ένα αντικείμενο
     * Πώλησης και ελέγχεται αν ο χρήστης έχει επιλέξει να αγοράσει κάποια
     * προϊόντα, τα οποία προσθέτει ως γραμμές πώλησης αφού πρώτα γίνουν οι
     * απαραίτητοι έλεγχοι.
     *
     */
    private void makeSale(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeSale

        // Δημιουργείται το αντικείμενο πώλησης
        reg.makeNewSale();

        // Έλεγχος διπλή επιλογής του ίδιου προϊόντος (ΠΡΟΑΙΡΕΤΙΚΟ)
        if (!checkProducts()) {
            //Αν βρεθεί διπλό προϊόν επιστρέφουμε στην φόρμα
            return;
        }

        // Για κάθε JCombobox επιλογήw προϊόντος ελέγχουμε αν ο χρήστης επελεξε ένα προϊόν
        for (int i = 0; i < productSelection.length; i++) {
            if (productSelection[i].getSelectedIndex() != -1) {
                //Ανακτούμε το επιλεγμένο προϊόν
                Item p1 = (Item) productSelection[i].getSelectedItem();

                try {
                    //Διαβάζουμε την ποσότητα που έχει βάλει ο χρήστης
                    int pos1 = Integer.parseInt(productQuantity[i].getText());
                    // Αν δεν δημιιουργηθεί πρόβλημα κατά την μετατροπή τη ποσότητα
                    // Δημιουργούμε και τοποθετούμε στην πώληση μία νέα γραμμή πώλησης
                    if (reg.enterItem(p1, pos1) == false) {
                        // Αν υπήρξε πρόβλημα κατά την εισαγωγή της γραμμής πώλησης
                        // δημιουργούμε εξαίρεση για να εμφανιστεί το αντίστοιχο μήνυμα
                        // και να σταματήσει η μέθοδος
                        throw new Exception();
                    }
                } catch (Exception x) {
                    //Εμφανίζεται το αντίστοιχο μήνυμα σφάλματος
                    JOptionPane.showMessageDialog(rootPane, "Παρακαλώ βάλτε θετικές " +
                            "ακέραιες ποσότητες στα αγαθά μικρότερες από τις διαθέσιμες");
                    // Ολοκληρώνεται η μέθοδος χωρίς να ολοκληρωθεί η πώληση
                    return;
                }
            }
        }

        // Αν όλα έχουν πάει καλά μπορούμε να προχωρήσουμε στην διαδικασία πληρωμής
        try {
            // Διαβάζουμε το ποσό που έβαλε ο χρήστης
            double amount = Double.parseDouble(jTextField6.getText());
            //Πραγματοποιεί την πληρωμή
            reg.makePayment(amount);
            // Ολοκληρώνουμε την πώληση εισάγοντας το ποσό που μας έδωσε ο χρήστης
            Receipt r = reg.endSale();
            // Αν η πώληση ολοκληρώθηκε χωρίς πρόβλημα
            if (r != null && r.isLegal()) {
                System.out.println(r);
                // Εμφανίζουμε τα στοιχεία στα αντίστοιχα πεδία και ολοκληρώνουμε
                // την φόρμα
                finalizeForm(r);
            } else {
                // Εμφανίζουμε μήνυμα ότι υπάρχει πρόβλημα και δεν μπορεί να ολοκληρωθεί
                // η πώληση
                JOptionPane.showMessageDialog(rootPane, "Δεν μπόρεσε να ολοκληρωθεί " +
                        "η συναλλαγή\n Ελέγξετε τα επιλεγμένα προϊόντα, τις ποσότητες " +
                        "και το ποσό.");
            }
        } catch (Exception x) {
            //Υπήρξε πρόβλημα με το ποσό πληρωμής και εμφανίζουμε το αντίστοιχο μήνυμα
            JOptionPane.showMessageDialog(rootPane, "Παρακαλώ βάλτε θετικές " +
                    "ακέραιες ποσότητες στο ποσό πληρωμής");
            return;
        }
    }//GEN-LAST:event_makeSale

    /**
     * Επιστροφή στην αρχική φόρμα αν πατηθεί ακύρωση
     *
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Ενεργοποίησε την αρχική φόρμα
        parentForm.setEnabled(true);
        //Απελευθέρωσε την τρέχουσα φόρμα
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * Επιστροφή στην αρχική φόρμα αν πατηθεί το Χ για το κλείσιμο της φόρμας
     *
     */
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        //Ενεργοποίησε την αρχική φόρμα
        parentForm.setEnabled(true);
        //Απελευθέρωσε την τρέχουσα φόρμα
        dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * Έλεγχος διπλή επιλογής του ίδιου προϊόντος
     */
    private boolean checkProducts() {
        //Δημιουργουμε ένα Set που εξασφαλίζει ότι δεν μπορούν να υπάρχουν διπλές εγγραφές
        Set selections = new HashSet(productSelection.length);
        //Για όλα τις πιθανές επιλογές του χρήστη
        for (int i = 0; i < productSelection.length; i++) {
            // Έχει εισαχθεί ήδη ο αντίστοιχος κωδικός εμφανίζεται μήνυμα λάθους
            // και επιστρέφουμε false
            if (selections.contains(productSelection[i].getSelectedIndex())) {
                JOptionPane.showMessageDialog(rootPane,
                        "Παρακαλώ επιλέξτε διαφορετικά αγαθά για κάθε γραμμή πώλησης" +
                        "ή αυξήστε τις ποσότητες στην 1η επιλογή του προϊόντος");
                return false;
            }
            //Εισάγουμε τον κωδικό του προϊόντος στο Set
            if (productSelection[i].getSelectedIndex() != -1) {
                selections.add(productSelection[i].getSelectedIndex());
            }
        }
        //Όλα πήγαν καλά και επιστρέφουμε true
        return true;
    }

    /**
     *
     * Η μέθοδος ολοκληρώνει την φόρμα ενημερώνοντας κάποια πεδία
     *
     * @param r Η απόδειξη
     */
    @SuppressWarnings("static-access")
    private void finalizeForm(Receipt r) {
        // Ενημερώνει το πεδίο για το σύνολο
        jLabel7.setText(String.format("%.2f", r.getTransaction().getTotal()));
        // Θέτει το πεδίο εισαγωγής του ποσού ως αμετάβλητο από το χρήστη
        jTextField6.setEditable(false);
        // Ενημερώνει το πεδίο για τα ρέστα
        jLabel10.setText(String.format("Ρέστα: %.2f Euro", r.getTransaction().getReturnedAmount()));
        //Απενεργοποιεί το κουμπί ολοκλήρωσης της συναλλαγής
        jButton1.setEnabled(false);
        //Για λόγους λειτουργικότητας αλλάζει το κείμενο και το χρώμα του κουμπιού ακύρωσης
        jButton2.setBackground(Color.GREEN);
        jButton2.setText("Επιστροφή");
    }

    /**
     * Δημιουργούμε ένα δικό μας μοντέλο για JComboBox ώστε να μπορούμε να
     * έχουμε εσωτερικά ώς πεδίο αναφορά στα αντικείμενα του καταστήματος
     */
    class ProductsModel extends javax.swing.DefaultComboBoxModel {

        ArrayList<Item> products = reg.getProductCatalog().getProducts();

        @Override
        public int getSize() {
            return products.size();
        }

        @Override
        public Object getElementAt(int i) {
            return products.get(i);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
